### ISSUE TITLE
Devolver a mensagem de erro para o front

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [rpmhub/revision#2]

**Comment by rodrigoprestesmachado** [comment]
Ajustar as mensagens de erro para o formato json

**Comment by psantunes** [comment]
Configurada a RevisionService.java para retornar responses em Json e criada uma mensagem de êxito.
No arquivo RevisionServiceException.java as exceptions também foram configuradas com o mesmo formato de mensagem de êxito.
